### ISSUE TITLE
Unable to download models - download_models.py 

### ISSUE THREAD

**Issue by prateekralhan** [kylegallatin/machine-translation-service#1]
I tried to download the files using the script doanload_models.py but I get this outiput :
![Untitled3](https://user-images.githubusercontent.com/29462447/84616571-06ed0b80-aeea-11ea-8a95-31afc0ac25a0.png)

Do they don't provide the s3 instance for downloading the models as I don't encounter HTTPerror generally when I try to fetch data from web. Also, I don't have any proxy set up in my system. 

OS: Windows 10 Home Version 1909

Python: 3.7.7 - 64 bit
Transfomers version: 2.0.0

**Comment by kylegallatin** [comment]
Ah. I think this is just because I used `os.path.join` to create the url dynamically, which on windows will create the path with backslashes.

**Comment by kylegallatin** [comment]
Latest push to master just now should've resolved this.

**Comment by prateekralhan** [comment]
@kylegallatin , works like a gem now 👍 thanks a ton :)
