### ISSUE TITLE
add sentencepiece to Docker requirements.txt

### ISSUE THREAD

**Issue by vvilliers-DTW** [kylegallatin/machine-translation-service#7]
Hi @kylegallatin ,

Loading translate() method with Docker image issues this message on my end:
```
MarianTokenizer requires the SentencePiece library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/google/sentencepiece#installation and follow the ones
that match your environment.
```
Adding sentencepiece to requirements.txt solved the issue.

**Comment by kylegallatin** [comment]
Thanks for letting me know, I've added it. As I didn't pin these to a version, they're likely to occasionally go out of date.
